using UnityEngine;
using System.Collections;

public enum AnimalActionType {
	NONE,
	IDLE,
	RUNNING_RANDOMLY,
	TELEPORT_TO_RANDOM_POS,
	FOLLOWING_PLAYER,
	PICKUP_LOOT,
	RUN_AROUND_PLAYER,
	RUN_AROUND_VILLAGE,
	WAKEUP,
	RUNOUTOFSCREEN,
	IDLEVILLAGE,
	EATING,
    RUN_TO_TELEPORTER,
    RUN_TO_REST,
    TELEPORT_TO_JUNKYARD
}
